import { AccessControlConfig } from './access-control.types';

export const ACCESS_CONTROL_CONFIG: AccessControlConfig = {
  fallbackRoute: '/error-404',
  apiPrefix: '/api/v1',
  moduleMap: {
    lab: 'laboratories',
    laboratory: 'laboratories',
    laboratories: 'laboratories',
    bank: 'banks',
    banks: 'banks',
    user: 'users',
    users: 'users',
    roles: 'user',
    'pharmaceutical-forms': 'pharmaceutical-forms',
    pharmaceutical_forms: 'pharmaceutical-forms',
    pharmaceuticalforms: 'pharmaceutical-forms',
    unit: 'units',
    units: 'units',
    'product-groups': 'product-groups',
    product_groups: 'product-groups',
    productgroups: 'product-groups',
    project: 'projects',
    projects: 'projects',
    return: 'return-units',
    'return-units': 'return-units',
    return_units: 'return-units',
    returnunits: 'return-units',
    'courier-companies': 'couriers',
    courier_companies: 'couriers',
    couriercompanies: 'couriers',
    'courier-company': 'couriers',
    courier_company: 'couriers',
    courier: 'couriers',
    couriers: 'couriers',
    supply: 'supplies',
    supplies: 'supplies',
    'simple-items': 'supplies',
    simple_items: 'supplies',
    'dry-package': 'supplies',
    'refrigerated-package': 'supplies',
    locations: 'locations',
    state: 'locations',
    states: 'locations',
  },
};
